node {
    ansiColor('xterm') {
        git url: 'git@github.com:jrasell/nomadfiles.git'
        def nomad_docker = docker.image('djenriquez/nomad:v0.5.4')
        nomad_docker.pull()

        def nomad_job = "${env.JOB_NAME}".tokenize( '_' )[1]

        stage 'dynamic update of job parameters'

        sh("sed -ie 's/NOMAD_PARAM_${env.JOB_NAME}_command/${command}/g' ./${nomad_job}/${nomad_job}.nomad")
        sh("sed -ie 's/NOMAD_PARAM_${env.JOB_NAME}_version/${version}/g' ./${nomad_job}/${nomad_job}.nomad")

        echo 'job syntax validation'
        nomad_docker.inside {
              sh """
              nomad validate\
              ./${nomad_job}/${nomad_job}.nomad
              """
        }

        stage 'plan job'
        nomad_docker.inside {
              sh """
              nomad plan\
              -address=http://${nomad_url}:4646\
              ./${nomad_job}/${nomad_job}.nomad || true
              """
        }

        stage 'run job'
        nomad_docker.inside {
              sh """
              nomad run\
              -address=http://${nomad_url}:4646\
              ./${nomad_job}/${nomad_job}.nomad
              """
        }
    }
}
